Implemented zstd, xz, bzip2 compression support.

diff --git a/vackup b/vackup
--- a/vackup
+++ b/vackup
@@ -16,129 +16,148 @@ handle_error() {
 trap 'handle_error $LINENO' ERR
 
 usage() {
-cat <<EOF
+cat >&2 <<"EOF"
 
 "Docker Volume Backup". Replicates image management commands for volumes.
 
 export/import copies files between a host tarball and a volume. For making
   volume backups and restores.
 
-save/load copies files between an image and a volume. For when you want to use 
+save/load copies files between an image and a volume. For when you want to use
   image registries as a way to push/pull volume data.
 
-Usage: 
+Usage: vackup COMMAND [ARG..]; FILE args must have known suffixes:
+  FILE = .{ tar[.{ gz | bz2 | xz | zst[d] }] | tgz | txz }
 
 vackup export VOLUME FILE
-  Creates a gzip'ed tarball in current directory from a volume
+  Create a (compressed) tarball in current directory from a volume.
 
 vackup import FILE VOLUME
-  Extracts a gzip'ed tarball into a volume
+  Extract a tarball into a volume.
 
 vackup save VOLUME IMAGE
-  Copies the volume contents to a busybox image in the /volume-data directory
+  Copy volume contents to the /volume-data directory of a busybox image.
 
 vackup load IMAGE VOLUME
-  Copies /volume-data contents from an image to a volume
+  Copy /volume-data contents from an image to a volume.
+
+Environment: $VACKUP_FAILURE_SCRIPT, $VACKUP_COMPRESS
 
 EOF
 }
 
-if [ -z "$1" ] || [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
-    usage
+msg() {  # args: exit_code msg
+    printf >&2 '%s\n' "$2"
+    return "$1"
+}
+
+if [ $# = 0 ] || [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
+    usage 2>&1  # print usage to stdout on request (unlike on error)
     exit 0
 fi
 
+detect_compression() {  # args: filename (de)compress-flag
+    [ -z ${VACKUP_COMPRESS:-} ] || return 0
+    case "$1" in
+        (*.tar)  VACKUP_COMPRESS=cat ;;
+        (*.gz)   VACKUP_COMPRESS=gzip ;;
+        (*.tgz)  VACKUP_COMPRESS=gzip ;;
+        (*.bz2)  VACKUP_COMPRESS=bzip2 ;;
+        (*.xz)   VACKUP_COMPRESS=xz ;;
+        (*.txz)  VACKUP_COMPRESS=xz ;;
+        (*.zst)  VACKUP_COMPRESS=zstd ;;
+        (*.zstd) VACKUP_COMPRESS=zstd ;;
+        (*)
+          msg 1 "Error: unknown extension ${1##*.}"
+          ;;
+    esac
+    command -v "$VACKUP_COMPRESS" >/dev/null ||
+      msg 1 "Error: $VACKUP_COMPRESS not available on host"
+    [ "$VACKUP_COMPRESS" = cat ] || VACKUP_COMPRESS="$VACKUP_COMPRESS $2"
+}
+
 cmd_export() {
-    VOLUME_NAME="$2"
-    FILE_NAME="$3"
-    
-    if [ -z "$VOLUME_NAME" ] || [ -z "$FILE_NAME" ]; then
-        echo "Error: Not enough arguments"
+    if [ $# != 3 ]; then
         usage
-        exit 1
+        msg 1 "Error: wrong number of arguments"
     fi
-    
-    if ! docker volume inspect --format '{{.Name}}' "$VOLUME_NAME";
+
+    VOLUME_NAME=$2
+    FILE_NAME=$3
+
+    detect_compression "$FILE_NAME" -c
+
+    if ! docker volume inspect --format '{{.Name}}' "$VOLUME_NAME" >/dev/null 2>&1
     then
-        echo "Error: Volume $VOLUME_NAME does not exist"
-        exit 1
+        msg 1 "Error: Volume $VOLUME_NAME does not exist"
     fi
 
 # TODO: check if file exists on host, if it does
 # create a option for overwrite and check if that's set
-# TODO: if FILE_NAME starts with / we need to error out
-# unless we can translate full file paths
 
-    if ! docker run --rm \
+    set -- docker run --rm \
       -v "$VOLUME_NAME":/vackup-volume \
-      -v "$(pwd)":/vackup \
       busybox \
-      tar -zcvf /vackup/"$FILE_NAME" /vackup-volume;
-    then
-        echo "Error: Failed to start busybox backup container"
-        exit 1
+      tar -cvf - /vackup-volume  # tar -vf - outputs list to stderr
+    if ! "$@" | $VACKUP_COMPRESS >"$FILE_NAME"; then
+        msg 1 "Error: Failed to start busybox backup container"
     fi
 
-    echo "Successfully tar'ed volume $VOLUME_NAME into file $FILE_NAME"
+    msg 0 "Successfully tar'ed volume $VOLUME_NAME into file $FILE_NAME"
 }
 
 cmd_import() {
-    FILE_NAME="$2"
-    VOLUME_NAME="$3"
-    
-    if [ -z "$VOLUME_NAME" ] || [ -z "$FILE_NAME" ]; then
-        echo "Error: Not enough arguments"
+    if [ $# != 3 ]; then
         usage
-        exit 1
+        msg 1 "Error: wrong number of arguments"
     fi
-    
-    if ! docker volume inspect --format '{{.Name}}' "$VOLUME_NAME";
+
+    FILE_NAME=$2
+    VOLUME_NAME=$3
+
+    detect_compression "$FILE_NAME" -d
+
+    if [ ! -r "$FILE_NAME" ]; then
+        msg 1 "Error: Cannot open \"$FILE_NAME\""
+    fi
+
+    if ! docker volume inspect --format '{{.Name}}' "$VOLUME_NAME" >/dev/null 2>&1
     then
-        echo "Error: Volume $VOLUME_NAME does not exist"
+        msg 0 "Warning: Volume $VOLUME_NAME does not exist, will be created"
         docker volume create "$VOLUME_NAME"
     fi
 
-# TODO: check if file exists on host, if it does
-# create a option for overwrite and check if that's set
-# TODO: if FILE_NAME starts with / we need to error out
-# unless we can translate full file paths    
-
-    if ! docker run --rm \
+    set -- docker run --rm -i \
       -v "$VOLUME_NAME":/vackup-volume \
-      -v "$(pwd)":/vackup \
       busybox \
-      tar -xvzf /vackup/"$FILE_NAME" -C /; 
-    then
-        echo "Error: Failed to start busybox container"
-        exit 1
+      tar -xvf - -C /
+    if ! $VACKUP_COMPRESS <"$FILE_NAME" | "$@" >&2; then
+        msg 1 "Error: Failed to start busybox container"
     fi
 
-    echo "Successfully unpacked $FILE_NAME into volume $VOLUME_NAME"
+    msg 0 "Successfully unpacked $FILE_NAME into volume $VOLUME_NAME"
 }
 
 cmd_save() {
-    VOLUME_NAME="$2"
-    IMAGE_NAME="$3"
-
-    if [ -z "$VOLUME_NAME" ] || [ -z "$IMAGE_NAME" ]; then
-        echo "Error: Not enough arguments"
+    if [ $# != 3 ]; then
         usage
-        exit 1
+        msg 1 "Error: wrong number of arguments"
     fi
 
-    if ! docker volume inspect --format '{{.Name}}' "$VOLUME_NAME"; 
+    VOLUME_NAME=$2
+    IMAGE_NAME=$3
+
+    if ! docker volume inspect --format '{{.Name}}' "$VOLUME_NAME"
     then
-        echo "Error: Volume $VOLUME_NAME does not exist"
-        exit 1
+        msg 1 "Error: Volume $VOLUME_NAME does not exist"
     fi
 
     if ! docker run \
       -v "$VOLUME_NAME":/mount-volume \
       busybox \
-      cp -Rp /mount-volume/. /volume-data/;
+      cp -Rp /mount-volume/. /volume-data/
     then
-        echo "Error: Failed to start busybox container"
-        exit 1
+        msg 1 "Error: Failed to start busybox container"
     fi
 
     CONTAINER_ID=$(docker ps -lq)
@@ -146,44 +165,46 @@ cmd_save() {
     docker commit -m "saving volume $VOLUME_NAME to /volume-data" "$CONTAINER_ID" "$IMAGE_NAME"
 
     docker container rm "$CONTAINER_ID"
-  
-    echo "Successfully copied volume $VOLUME_NAME into image $IMAGE_NAME, under /volume-data"
+
+    msg 0 "Successfully copied volume $VOLUME_NAME into image $IMAGE_NAME, under /volume-data"
 }
 
 cmd_load() {
-    IMAGE_NAME="$2"
-    VOLUME_NAME="$3"
-    
-    if [ -z "$VOLUME_NAME" ] || [ -z "$IMAGE_NAME" ]; then
-        echo "Error: Not enough arguments"
+    if [ $# != 3 ]; then
         usage
-        exit 1
+        msg 1 "Error: wrong number of arguments"
     fi
 
-    if ! docker volume inspect --format '{{.Name}}' "$VOLUME_NAME"; 
+    IMAGE_NAME=$2
+    VOLUME_NAME=$3
+
+    if ! docker volume inspect --format '{{.Name}}' "$VOLUME_NAME"
     then
-      echo "Volume $VOLUME_NAME does not exist, creating..."
+      msg 0 "Volume $VOLUME_NAME does not exist, creating..."
       docker volume create "$VOLUME_NAME"
     fi
-    
+
     if ! docker run --rm \
       -v "$VOLUME_NAME":/mount-volume \
       "$IMAGE_NAME" \
-      cp -Rp /volume-data/. /mount-volume/; 
+      cp -Rp /volume-data/. /mount-volume/
     then
-        echo "Error: Failed to start container from $IMAGE_NAME"
-        exit 1
+        msg 1 "Error: Failed to start container from $IMAGE_NAME"
     fi
 
-    echo "Successfully copied /volume-data from $IMAGE_NAME into volume $VOLUME_NAME"
+    msg 0 "Successfully copied /volume-data from $IMAGE_NAME into volume $VOLUME_NAME"
 }
 
-COMMAND="$1"
+COMMAND=$1
 case "$COMMAND" in
-  export) cmd_export "$@" ;;
-  import) cmd_import "$@" ;;
-  save) cmd_save "$@" ;;
-  load) cmd_load "$@" ;;
+  (export) cmd_export "$@" ;;
+  (import) cmd_import "$@" ;;
+  (save) cmd_save "$@" ;;
+  (load) cmd_load "$@" ;;
+  (*)
+      usage
+      msg 1 "Error: Unknown operation $COMMAND"
+      ;;
 esac
 
 exit 0
